### ISSUE TITLE
Use Kutes JS instead of data attributes, is it possible?

### ISSUE THREAD

**Issue by JensB74** [thednp/spicr#1]
Sorry, it is probably my insufficient knowledge of Javascript ...

Is it possible to use the kute.js functions instead of the data attributes and if so, how? 
And is it the same functionality for the slider or is it only possible to set the animations by the attributes?

I.E. I want these attributes:
data-translate="y:250" data-duration="600" data-rotate="z:15deg" data-easing="easingCubicInOut"
not in the HTML area but in Javascript area, because it's easier for the Content Managament System (the WYSIWYG Editor) to handle it without the attributes ...

Thanks in advance and thanks for the great Spicr and Kute modules!
Greetings from Germany and a happy new Year!

**Comment by thednp** [comment]
> Is it possible to use the kute.js functions instead of the data attributes and if so, how?

Not everything is possible via JavaScript only without heavy changes to the Spicr.js core scripting. The implementation of attributes is key to enabling easy and complete animation control.

> And is it the same functionality for the slider or is it only possible to set the animations by the attributes?

You can initialize your elements via JavaScript by providing options to initialization and ignore their corresponding attributes like `data-touch` or `data-interval` but the animation control related options are set via attributes. The idea is to leave the door open for the opportunity to change these data values for every slide and every layer on every animation cycle, which is the reason why we always check for these attributes before every animation.

Read the demo page carefully, you will find slider and carousel are two separate feature sets, and they both require attributes to control animations.
